[build]
  command = 'export PATH=./.ci/bin/:"$PATH" && build-netlify'
  publish = 'www'

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[plugins.local.server]
  static = true
  lambda = false
  port = 8100
